### ISSUE TITLE
章立てについて

### ISSUE THREAD

**Issue by sickleaf** [onestop-techbook/c93-onestop-techbook#12]
病葉(@sickleaf3)と申します、よろしくお願いします。

既に章の追加が始まっているので不要かもしれませんが、工程ごとに章を分類してみては如何でしょうか。
現在の章立てのレベルだと、大まかな全体の工程が掴みにくいのでは…と感じたためです。

また、全工程の中で少し知ってるものがあるとメリハリを付けて読みやすくなるのではないかと思います。
（例：テーマが明確にある人は§1は読み飛ばせる、売り子を経験した人は§4は軽く読める、など）

現在の章立てを（独断で）割り振ったものは下記の通りです。
良さげかそれとも余計なお世話か、ご意見下さい。。

＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝

§1. テーマ決定・参加表明
>4.　技術書オンリー+コミケ　参加のメリット
>5.　ネタ出し法
>12.　次の締切を手に入れよう
>14.　コミュニティに参加する

§2. 環境構築・執筆
>3.　この本の執筆環境について
>6.　執筆環境について
>14.　コミュニティに参加する

§3. 印刷所
>7.　印刷業者に頼むためのTips

§4. サークル運営
>8.　当日までの準備
>9.　当日朝、開場までの準備
>10.　開催中のTips
>11.　イベント終わってからやること
>13.　委託しよう

§5. お金
>15.　お金の話

＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝

![tableofcontents-suggestion-min](https://user-images.githubusercontent.com/5824061/32500943-1783ee22-c41a-11e7-8a2d-e34af9ee464a.JPG)

**Comment by oyakata2438** [comment]
おやかたです。
ステキな意見ありがとうございます。
いいですね。確かにすっきりしますね。

中身は微調整しつつ、一旦この方向でいってみましょうか。
（といっても、特段現時点での執筆に関して何か変わるわけではなかろうかと思いますが…

何か意見ありましたら、
あるいは、手戻し等発生しそうなら、コメント、意見ください。

**Comment by oyakata2438** [comment]
本文が70ページを超え、そろそろ全体感が見えてきた頃かと思います。

執筆頂いています皆様、本当にありがとうございます。

以下、お願いです。
（1）誰か？？？のネタについて書いてー、というネタがあれば、
== 誰か書いて：税金の話
という感じで、節のレベルで、
16-tempTopix.reの最後に記載ください。
で、それを見つけた方、ぜひ執筆お願いします。

（2）コラムはぜひたくさん入れてください。
で、コラムタイトルのあとに、署名をお願いします。
====[column] ネタ出し : 親方
と言った形でお願いします。

（3）途中でも構いませんので、全体感把握/重複抑止のため、
適宜Pushまたはプルリクで進捗共有お願いします。
目次だけでも全く問題ありませんので、よろしくお願いします。
