### ISSUE TITLE
印刷部数と頒布場所の相談

### ISSUE THREAD

**Issue by oyakata2438** [onestop-techbook/c93-onestop-techbook#16]
親方です。

執筆ありがとうございます。
そろそろ印刷部数を考えようかと思い…
200にするとか、300にするか・・・（あるいはもっと？それは流石に・・・？

で、それに先立ち、皆様のサークル参加の予定を教えてください。
一日目は、まとめて親方Projectに搬入し、中で運べば良いのですが、
三日目は、誰かのところに直接搬入し、その後運ぶとか必要になります。
ですので、まずは、
参加日、配置場所
配布していただけるかどうか。部数。
を回答いただければと思います。
それを合算したり丸めたり水増ししたりして、印刷部数を考えたく思います。

**Comment by ykichinomiya** [comment]
３日目 東"リ"05bです。
頒布可能ですが、ジャンル違い(創作イラスト島)なので売上げは見込めないです。
恐らく10部程度かと(汗

**Comment by MofuMofu2** [comment]
もふもふです。
コミケは一般参加組です😥
お手伝いできず申し訳ないです。

**Comment by llminatoll** [comment]
すみませんが、私も一般参加になります； 

これはアイデアベースですが
技術書典4（開催されればですが）でも販売するという見込みがあれば
技術書典でトータル100部ぐらいはさばけるかもしれませんね！
（技術書典で、いろんなサークルに分散して置くとか）

**Comment by oyakata2438** [comment]
そういえば、うちの場所を書くのを忘れてました…
1日目カ-41b、同人ソフトの電子工作島の中です。

多分、うちが70～100行くといいなーというくらいかと思ってます。
といいつつ、いつもの続きものと全く別の本なので、どれくらい出るかわからない…

残った分は当然技術書典4でも出しますw
在庫置き場をとるか、印刷費をとるかという相反する問題ががががw

**Comment by llminatoll** [comment]
> 残った分は当然技術書典4でも

確かにそのほうが安全そうですね！ありがとうございます！

**Comment by erukiti** [comment]
技術書典4でも頒布はできたらしたいですね。ただその分を今からするのか、第二版にするのかは…

**Comment by oyakata2438** [comment]
ページ数がかなり多いので、部数を減らすと印刷費がかなり厳しいことになります。
192Pとして、100部125千円、200部で143k。300部で168千円。
えげつないカーブですね・・・

ですから、100冊というのは印刷費用的にありえません。
（本の中身的には、継続的に売れる内容である期待もあります。

なので、一旦200印刷予定。置き場所には困るのですが。
150から180くらいは1日目に持っていきます。
ゆきさんとこにも、置いてもらえるなら、直接搬入かけます。

そして、価格はどうしようかな、というところ。
技術書初心者向けということで、1000円にしたかったのだけど、
厚みと印刷費的に厳しいので、2000円かなーと思ってます。

**Comment by degawa** [comment]
頒布場所は
親方さん 1日目カ41b
ゆきさん ３日目リ05b
で告知すればよろしいでしょうか?

**Comment by degawa** [comment]
すみません、別ISSUEに書いてありましたね
