### ISSUE TITLE
レイアウトどうします？

### ISSUE THREAD

**Issue by erukiti** [onestop-techbook/c93-onestop-techbook#2]
レイアウトどうします？
もうちょっと字を詰めてもいいかなーと思ったりしています。

**Comment by oyakata2438** [comment]
全体厚くなると思うので、文字は詰めていいと思います。
上下はスペース削って・・・だんだん執筆者も増えてきて、まだ時間があるので・・・どこまで増えるかw

ノドと小口はもう少し書き進んで、お試し出力してみて、でしょうか…
行間はこんなもんでしょうかね。それもお試し印刷で確認、という感じで。
