### ISSUE TITLE
Wordの章

### ISSUE THREAD

**Issue by degawa** [onestop-techbook/c93-onestop-techbook#44]
皆様：
標記の件、Wordの章だけ内容が浮いているように思います。
Re:VIEWに焦点を当てた方が内容がまとまりますので、自身で追加しておいて何ですが、今回は削除してしまってよろしいでしょうか？

**Comment by oyakata2438** [comment]
Re:VIEWで押し/推しているので、流れ的には浮くのはご指摘のとおりかと思いますが…
Wordで書いてる人もいるはずなので残したいです(私も基本Word執筆なので・・・)

なので、執筆環境構築(１章)と合わせて、Appendix回しでどうでしょう。
１章もいきなりこの内容は割とハードル高いのと、Re:VIEWの概要は現5章に入ってるので…

**Comment by degawa** [comment]
わかりました．
ではAppendixにするという方針で，それを意識した文章にします．
できる限り急ぎます．

**Comment by degawa** [comment]
原稿を書いてプルリクエストを送ったので，クローズします．
