### ISSUE TITLE
レビューのお願い／レビュー方法について

### ISSUE THREAD

**Issue by oyakata2438** [onestop-techbook/c93-onestop-techbook#48]
目次確定から、ほぼ全体の執筆が終わって、
あとは画像張り込みとか、本文微調整のフェーズに来たかと思ってます。
つきましては、そろそろ執筆者間でのレビュー、添削・推敲をやらねば。。。です。

で、その方法について、一旦以下のように考えてます。

○明らかな誤字については、見つけた人がその場で直してOKです。
あるいは、まとめて、セクション番号と何行目どこどこに誤字あり、をつらつら書く。
　(その章執筆者が直すか、親方の方で直します)
○見解の相違については、ここに記載お願いします。相談しましょう。
　章x.y.zには、こういうときにはhogeしたらよいと書いてあるが、それは運営によって禁止されてるよ
　章x.z.yの持ち物リストの順番を変えた方が良いと思う。
などなど。

その他、なんでもコメントください。よろしくお願いします。

合わせて、まだ目次のみの部分については、7日24時を一旦の期限として、UPお願いします。

**Comment by degawa** [comment]
入稿する原稿の画像はカラーのままでも大丈夫なのでしょうか？

**Comment by oyakata2438** [comment]
印刷所によっては、本文カラーのままでも「適当に」グレースケール変換してくれるところもありますが、
今回の本については、中表紙入れたり、塗り足しサイズ変えたりする時に本文グレースケール化します。
なので、特に画像データのグレースケール化は不要です。

**Comment by oyakata2438** [comment]
追伸：明らかに見づらくなるような場合は、別途修正依頼出します。

**Comment by degawa** [comment]
承知しました．では先に本文のレビューを進めます．

**Comment by MofuMofu2** [comment]
@oyakata2438 さん、ちょうど今本文を読み進めていますが質問があります:smile:
レビューの締め切りはいつ頃までがよろしいでしょうか？

たしか10日に入稿されると伺っていますが、
直前に修正点をpushしちゃうとご迷惑かな:thinking:と思い質問させていただきました。

**Comment by oyakata2438** [comment]
入稿は11日夜の予定ですから、土曜日夜くらいまでは問題ありません。
（あとでトップページ更新しておきます）

修正量が多いなら早めに上げてもらえると助かりますが。
重大なミスがあれば、ギリギリまで対応します。（それは対応しないと印刷に出せないので

**Comment by MofuMofu2** [comment]
了解です！そんなに量はおおくないと思いますので、土曜の午前中までにpushします:smile:

**Comment by ykichinomiya** [comment]
うっかり直接pushしてしまいました。
いろいろ不慣れですみません(-_-;)

**Comment by erukiti** [comment]
わりと重複気味なところ削ったりとかはかんがえます？

**Comment by oyakata2438** [comment]
個人的意見としては、通しで読むのもいいのですが、
辞書的に使うのが目的の一つなので、ダダ被りの部分を除いては残しでいいんじゃないかと。
パラっと開いたら、そこにノウハウが書いてある、的に使ってもらえればと。

といいつつ、皆さんの意見も聞きたいですね。

あと、どことどこが重複気味だかと思う、を上げて頂けると・・・
これなら残してもいいかな/どっちかに寄せよう、と考えやすいかと思います。

**Comment by erukiti** [comment]
あー、でも通して今読んでるんですが、悪くない程度の重複具合かなーという気はしました

**Comment by oyakata2438** [comment]
最終作業に入りますので、一旦執筆、レビューとも締め切りとします。
重大な何か、どうしても入れたい何かが出たら、相談してください。
