### ISSUE TITLE
表紙どうしましょう

### ISSUE THREAD

**Issue by oyakata2438** [onestop-techbook/c93-onestop-techbook#5]
親方です。

表紙をどうするか、ご意見ください。
技術書でよくあるパターンはだいたい以下の3つ。
（1）萌え系イラスト
（2）オライリーオマージュ系（単色の動物とか）
（3）フリー写真とか。

（1）なら、どこから調達するかも検討必要ですね。。。
クラウドソーシングなら、15k程度、1ヶ月ちょい。今なら問題ないスケジュールです。
誰かに頼む場合、誰にお願いするか、という問題がありますが・・・

（2）（3）も誰が作るか、という問題がありまして・・・悩ましいところです・・・

**Comment by erukiti** [comment]
コミケで手にとってもらうことを考えると1は強そうですね

**Comment by llminatoll** [comment]
湊川です。親方さんにお声がけいただき、

- 表紙イラスト
- 「14.　コミュニティに参加する」の執筆（2〜3ページ）

で参加させていただくことになりました！

よろしくお願いします。

**Comment by llminatoll** [comment]
## 表紙について
![ieksg4a5](https://user-images.githubusercontent.com/22927920/32688070-41480bf8-c70d-11e7-9e9f-9b3beacc7558.png)

このような形で、1枚絵で、表1-4続きで使おうかという話になっております！

## 親方さんより
- 「技術系同人誌を書こう」なので、なんかそれっぽく
- キャラクターは、おまかせ（できればオリジナル）
- GAの本のイラストはすごくいい感じなんで、あんな感じに

**Comment by llminatoll** [comment]
表紙のラフ描きました〜

[![Screenshot from Gyazo](https://gyazo.com/440d16cb4e8bb1fea59797c2c6a0dec7/raw)](https://gyazo.com/440d16cb4e8bb1fea59797c2c6a0dec7)

## 絵にこめたストーリー
技術系同人誌の作り方ということなので
　キャラクターが手元のCUIで `$ rake clean pdf` なりする
　→PDFがジェネレートされた！
的なイメージです。

## キャラクター
赤と黒の毛皮の、スカンクの天使です。今日考えました。
名前はまだないので、よかったら決めてあげてください。

備考：ポケットに製本用ホッチキスとか入れたい

**Comment by llminatoll** [comment]
## タイトルの位置
タイトル入れるとしたらここらへんですかね？

[![Screenshot from Gyazo](https://gyazo.com/2e20b835bb6615649da836dc8cf99787/raw)](https://gyazo.com/2e20b835bb6615649da836dc8cf99787)

**Comment by llminatoll** [comment]
表1だけだとこんな感じ

[![Screenshot from Gyazo](https://gyazo.com/8dc20f05f40968c67a85b599b5f3d4a0/raw)](https://gyazo.com/8dc20f05f40968c67a85b599b5f3d4a0)

**Comment by llminatoll** [comment]
すみません、タイトルは「ワンストップ!技術同人誌を書こう(仮)」でしたね。
また絵が完成しましたら文字組しましょう。

**Comment by llminatoll** [comment]
タイトル直しました

[![Screenshot from Gyazo](https://gyazo.com/74d8772650013fa45d335547a50309b2/raw)](https://gyazo.com/74d8772650013fa45d335547a50309b2)

**Comment by MofuMofu2** [comment]
@llminatoll かわいいですー！ちなみにスカンクちゃん（仮）は女の子でしょうか？（男の子だったとしても可愛らしいですが）  
名前を考えるときに性別に沿ったものを考えたいなーと思いまして…。

**Comment by llminatoll** [comment]
@MofuMofu2 性別も決めてないですので、中性的な名前だといいですかね！
読者さんの好きに解釈してもらう感じで

**Comment by llminatoll** [comment]
進捗ですー
[![Screenshot from Gyazo](https://gyazo.com/f713926b7a825fd1c11f1e3f810774b1/raw)](https://gyazo.com/f713926b7a825fd1c11f1e3f810774b1)


▼加工かけるとこんな感じ？（まだ途中段階ですが）
[![Screenshot from Gyazo](https://gyazo.com/765564890ded02f275edddbb3e07b978/raw)](https://gyazo.com/765564890ded02f275edddbb3e07b978)

**Comment by llminatoll** [comment]
@oyakata2438 
表紙絵できました！ご確認のほどよろしくお願いします。

![onestop-techbook _2](https://user-images.githubusercontent.com/22927920/32903031-4e530b12-cb37-11e7-8134-ba0c5fb92a1f.png)

問題なければPSDファイルをお送りします。

**Comment by llminatoll** [comment]
A5で大丈夫でしたか？
[![Screenshot from Gyazo](https://gyazo.com/8fe72f57fc583aa9705f24e6bab6be2d/raw)](https://gyazo.com/8fe72f57fc583aa9705f24e6bab6be2d)

いつも使ってるテンプレに当て込めたものです

**Comment by oyakata2438** [comment]
ありがとうございます！

すばらしいです・・・

本のサイズはB5です（多分A5だと、厚くなりすぎるので…）
お手数おかけしますが変更お願いします。

**Comment by llminatoll** [comment]
ご確認いただきありがとうございます！
B5、承知しました〜！

**Comment by llminatoll** [comment]
@oyakata2438 B5のPSDファイル作りました〜
見た目はこんな感じです
PSDファイル置き場はTwitterDMで連絡した通りです！

[![Screenshot from Gyazo](https://i.gyazo.com/22036c861ae9f1845c85a8d5a0717f8a.png)

よろしくお願いします！

**Comment by llminatoll** [comment]
みなさまへ：
告知用画像2種類作ったので、告知のタイミングが来たら、よかったら、ツイッター用やブログ用に使ってください。

![default](https://user-images.githubusercontent.com/22927920/32931192-36f8afd4-cba6-11e7-8754-381435bcbdf7.png)
![2](https://user-images.githubusercontent.com/22927920/32931195-393768bc-cba6-11e7-8e1b-e96539162733.png)

- この本のための告知用なら、トリミングなどしていただいても構いません。
- もし可能であればツイートやブログに「イラスト：湊川あい @llminatoll 」と入れていただけると嬉しいです。

**Comment by oyakata2438** [comment]
表紙は確定したので・・・一旦このスレ閉じます。
必要に応じて再開、新規で…
