### ISSUE TITLE
みんなどうした？はじめてのあんなことやこんなこと

### ISSUE THREAD

**Issue by degawa** [onestop-techbook/c93-onestop-techbook#51]
皆さんの原稿を読んでいてふとネタが降りてきたのですが，本の趣旨に合わなさそうなのでメモ代わりに残しておきます．

私は技術書典2に参加するにあたって，印刷所を決めるのに1週間ほどかかりました．バックアップ印刷所5個すべてに見積もりを出してもらったりしました．
本書は技術同人誌を書こうと題されているだけあって，本を書くことや完成させること，参加することに関して非常に貴重な情報が詰まっていますが，これを読んで初めて同人誌を書いた方は，「結局印刷所決めんのはどないしたらええねん」となるのではないかなぁと感じています．

せっかくの合同誌で参加されている方も多いので，みなさんに質問を投げてその回答をまとめるのも有益かなと思います．
例えば「はじめての印刷所，どうやって決めた？」という質問に対して，印刷品質がよいとの評判があったので決めた，少し高いが原稿をチェックしてくれるときいた，など様々な視点からの答えがあると，着眼点の近い人の意見が参考になるのではないかと思います．

これはあくまで一例で，印刷所の口コミを作りたいわけではなく，みなさんが迷った/困ったことはこれから技術書を書く人も同じように迷う/困るだろうと考えられるので，「答え」ではなく「判断根拠」を知りたいなぁということです．

**Comment by azusa** [comment]
正直言うと、技術書典のサポート印刷所の中で、(主催の)techboosterさんが日光企画さんメインなのでそうした、以上の理由がないです。

**Comment by oyakata2438** [comment]
親方です。

いいですね。追加しましょうか。ぜひ、判断基準をコラムとして、載せてもらえるといいと思います。

ちなみに、うちは、
共信印刷：締切が遅い(オンデマ)
ポプルス：共信印刷の対応外の厚みと入稿タイミング(オンデマ)
栄光：絵師からオフセット印刷を勧められ、その中でやすかった。
K-9：オフセットで、栄光より安い。
いずれも、コミケへの直接搬入可能は必要条件。ということで、おもに印刷費で選んでます。

**Comment by degawa** [comment]
この件ですが，急いでまとめるよりは，どのような事でみんな困ったか（どのような項目があると初心者の助けになるか）の情報を集めてから，それらの質問を投げて回答を集めた方がよい気がします．本にするなら一つの章を丸ごと使ってとか．
10日に完成を目指しているとのことなので，今からやるとしてスケジュールはどうでしょうか？難しいなら改訂版で追加するか，あるいは今から集めてコピー本にする手もあります．

一方で，集められる分だけ集めてコラムに入れるのも一つのやり方だとは思いますし，印刷所の決め方はあった方がよいとも思います．

とりあえず印刷所を決める基準を集められるだけ集めてコラムに入れますか？

**Comment by ykichinomiya** [comment]
技術系同人誌の場合は同人に特化した印刷所を使う必要性は低いので、選択肢は広いと言えますよね。実績と品質を確認する手段としてはやはり「他のサークルさんの本の奥付を片っ端から調べる」が良いのではないでしょうか。

**Comment by sickleaf** [comment]
私はazusaさんと同じく、イベントのサポート印刷所の中から選びました。
執筆で手一杯で他の印刷所を調べる余裕もなく、日光企画・ねこのしっぽの２つのうち、より長い納期が確保できるプランのあった、ねこのしっぽに依頼した、という流れでした。
XeTeXで作成した私の入稿データにはノンブルが入っておらず、この本の"ノンブルが必須である印刷所"の章で日光企画さんはノンブル必須という表を見て背筋が寒くなりました。。
