### ISSUE TITLE
あとがきと著者紹介

### ISSUE THREAD

**Issue by erukiti** [onestop-techbook/c93-onestop-techbook#59]
そろそろあとがかないといけないのでは！？

というのと、著者紹介。アイコンも貼るとよいのでは？

**Comment by oyakata2438** [comment]
あとがきで、執筆者コメント お願いするの忘れてました…スミマセン・　・・
あとがき本文は今晩中に書きます。

＞えるきちさん
アイコンいいですね。
ただ、小さい絵を文中で入れる方法がわかってないので・・・例を入れてもらえませんでしょうか？

執筆者あとがきのお願いです。
本企画に参加した理由とか、参加してどうだったかとか、それ以外でもOKです。
一言づつお願いします。

このIssueでもよいですし、postscript.reへ直接記入でも構いません。
間際のお願いで本当に申し訳ないです。。。よろしくお願いします。

**Comment by erukiti** [comment]
あー、アイコンどうやって入れるんだろう…。試してみますが、もしかしたらLaTeX叩かないといけない(そしてLaTeXさっぱりわからない)

**Comment by degawa** [comment]
それならLaTeXで出来るのでやります

**Comment by erukiti** [comment]
一応、Re:VIEWの標準機能で試したバージョンが #63 です。LaTeXでうまくいけそうなら、それでお任せしたいです

**Comment by degawa** [comment]
画像が貼れないようようなのでURLで．
https://twitter.com/implict_none/status/939166100465389568
このような書式でよろしいでしょうか？
これはこれで縦の空白やアンダースコア，@を入れるのが大変そうですが，できないことはなさそうです．
これでよければ全員分のTwitterアイコンをダウンロードして//embed{}に流し込みます．

**Comment by oyakata2438** [comment]
素晴らしいです。

お手数おかけしますが…お願い致します。

**Comment by oyakata2438** [comment]
あとがきコメントまだの人、ぜひお願いします。
