### ISSUE TITLE
すすめかた

### ISSUE THREAD

**Issue by erukiti** [onestop-techbook/c93-onestop-techbook#7]
基本はプルリクを投げて、誰かがマージするという流れだと思うんですが、マージは現時点では僕がやっています。まぁたたき台を作るということで。

1つの手としては、メンバーの誰かがコメントで :+1: とか LGTM とかをコメントしたら、別の誰かがmergeボタンを押す、みたいなやり方です (よくチーム開発で使われてる)

もう1つは編集者を決めて編集者がマージする。

目次に名乗り上げた自分の章に関しては、自分が編集者としてとりあえず進めるのありかなと思います

**Comment by oyakata2438** [comment]
分担ももやっとしているので、書けるところから書いていくのも含めて、
細かくレビューしなくても順次マージしてしまって、全体を粗で作るのを優先したほうが早い気がします。
「編集者」にマージが集中してしまったり、そこがネックになるのもよろしくないですし。

**Comment by erukiti** [comment]
おー、なるほど。そうなってくると、直接リポジトリにpushでもいいかもしれないですね。それかPR投げて即マージか

**Comment by erukiti** [comment]
あ、chapterに関してなんですが、適当に01-writing.re というタイトル付けちゃいましたが、章が増えたり減ったりする場合面倒なので、数字無しの方がいいかもしれないです。

**Comment by oyakata2438** [comment]
全体感が早めに見えたほうが、「こっちはOKそうだから、こっち書こう」とか、
「誰かここ書いてー」とか、やりやすいと思います。
ソフトとちがって、「見えないバグ」が出るわけではないので、
レビューそこそこで良いとして、マージの敷居は下げてOKかと。
そして、いざとなれば巻き戻し可能なGitを使ってるメリットもそこ出ててくるかと。

**Comment by erukiti** [comment]
確かに。

pushなりmergeボタン即座に押すなりするということでいきましょうか。何か考えるのは考える必要が出てからでいいですしね
