### ISSUE TITLE
左右の余白が狭すぎて、製本すると綴じ代部分が読みにくい懸念がある

### ISSUE THREAD

**Issue by kauplan** [onestop-techbook/c93-onestop-techbook#87]
PDFを生成してみると、左右の余白が狭すぎるように思います。
このまま製本すると、綴じ代部分が読みにくいのではないかと懸念します。

特に今回は約200ページあるので、本の厚さが1cmを楽に超えます。
本が厚いと見開きが広げにくいので、綴じ代部分の読みにくさが顕著になりやすいです。
左ページの右余白と右ページの左余白を広げるか、または両ページの左右の余白を広げたほうがいいと思います。

具体的には、以下のことを提案します。
* 1行の文字数を45文字程度に減らす（現在は48文字）か、
* または文字数は同じままでフォントサイズを小さくする

市販の本との比較画像を作ったので参考にしてください。
https://pbs.twimg.com/media/DQpTsnWU8AA_P-E.jpg
これを見る限り、フォントサイズはもう少し小さくしても問題なさそうです。

締め切り日にこんなこと言うなよといわれそうですが、今言わないと後悔しそうなので、Issue登録しました。
最終的にどうするかの判断は、おまかせします（なにせ締め切り日なので）。

**Comment by erukiti** [comment]
おおおお、マジすか。ちょっと手元で実験してみます

**Comment by oyakata2438** [comment]
当日と言いつつ、まだ入稿までに時間はあるのでなんとかしましょう。

健康で文化的な入稿スケジュールですからw

**Comment by erukiti** [comment]
https://app.wercker.com/onestop-techbook/c93-onestop-techbook/runs/build/5a2c9eedf5917400013bc6e1
9pt 左右余白20mm

https://app.wercker.com/onestop-techbook/c93-onestop-techbook/runs/build/5a2ca08a9fe1e0000129f280
9.5pt 左右余白20mm

**Comment by erukiti** [comment]
https://app.wercker.com/onestop-techbook/c93-onestop-techbook/runs/build/5a2ca390f5917400013bc752?step=5a2ca3cf4267f3000144f7d7
9.5pt 左右余白16mm

ちなみに最初のやつは10pt 余白12mmです

**Comment by erukiti** [comment]
見開きの真ん中だけ広げるのはたぶんできるんですが、TeX詳しくなくてなんともです。

**Comment by oyakata2438** [comment]
9.5pt20mmでいきましょうか。

208Pに増えましたが、この際誤差ですw

あと、真ん中だけ広げるのは、1枚イラストとか何かをヤクザな方法で追加したときに破綻するのでなしでｗ

スタイルの設定ファイル更新が必要になりますかね。

**Comment by erukiti** [comment]
じゃぁ9.5pt 20mmのブランチのPR出します

**Comment by erukiti** [comment]
ちなみにですがコラムの位置入れ替えや、画像のリサイズでページ数多少減らせます

**Comment by oyakata2438** [comment]
減らす必要もないかと思いますw
技術系同人誌において、厚いは正義ですw

そして、圧縮に関わるミスのほうが怖いですし、手間も含めてw

これで確定としましょうか。

**Comment by kauplan** [comment]
ありがとうございました！
