### ISSUE TITLE
ページ構成

### ISSUE THREAD

**Issue by erukiti** [onestop-techbook/c93-onestop-techbook#90]
> あんしん BOOTH パック」+「宅急便コンパクト」:暗黙の型宣言

これに関してはコラムから普通の節の昇格した方がいいかもしれません。分量的に。

今回使ってるstyleだとコラムが複数ページにまたぐことができません

**Comment by erukiti** [comment]
あ、あとすみません。

> A.2.4 Windows Subsystem for Linux (Windows10)で環境を構築する

これ、間に合わなかったのでけしておいてくださいです。すみません

**Comment by degawa** [comment]
A.2.4消しています．
あんしんBOOTHパック＋宅急便コンパクトの件、書き始めの際にどこかの節か項にしようと思いましたし，分量も多いと感じます．16.1節の流れ的に割り込ませる場所がなかったので，独立したコラムにしています．
p.126が1行しか書かれていないので，それを補う意味でも16.1.6に昇格した方がよいでしょうか．

**Comment by erukiti** [comment]
編集方針次第ですが、16.1.6 に名前は入れなくてもいいかもしれません。
@oyakata2438 さんの判断次第

**Comment by degawa** [comment]
名前はコラムにしか入れていないので，私個人としては16.1.6 に名前は不要と思います．
