### ISSUE TITLE
打ち上げ日程調整の件

### ISSUE THREAD

**Issue by oyakata2438** [onestop-techbook/c93-onestop-techbook#95]
おかげさまで、昨晩無事入稿完了しました。
　印刷所からの連絡次第ですが…

1日目はカ41b　親方Project
三日目はリ05b　Clear-mint　ゆきさんところで販売です。

さて、入稿も終わったということで、打ち上げの予定を調整したく。
https://techbook-and-ethanol.connpass.com/event/71358/
も予定していたのですが、流石に大晦日開催は日程的に厳しいので、
1月中旬ごろかなー、などと。

つきましては…
まずは、一番遠いと思われる暗黙の型宣言さん、(何かの用事にからめて頂けるとベターですが)
来て頂ける日程ありますでしょうか？
そこを参考に調整したいと思います。

みなさんも、この日はダメ。というのがあれば教えてください。

ある程度うれたら、打ち上げがおごり、
たくさん売れたら、豪華になります。
大爆死したら、割り勘でお通夜になります(笑)

よろしくお願いします。

**Comment by degawa** [comment]
9, 12-14, 17, 28を避けていただければいつでも行けますよ。
29-31なら秋葉原UDX行く用事がありますが、さすがに遅いと思いますので、決めていただければ平日でも

**Comment by llminatoll** [comment]
親方さん、企画ありがとうございます。
湊川は

- 1/1-1/15以外
- 1/20以外

でしたら参加できます。
1/1-1/15は関西にいるので、基本的にはみなさんのご都合を優先していただければと！

**Comment by oyakata2438** [comment]
親方です。

1月中旬、本業のほうが忙しくなってしまいまして・・・
暗黙さんが来られるということで、29日（月）いかがでしょう？

1月中には実施したいので・・・OK／NG回答いただけますと幸いです。
ついでに、場所とか、飲み屋希望あれば（和食、中華、洋食がいい、あるいはこの店がいい、など）

よろしくお願いします～

**Comment by degawa** [comment]
Looks Good To Me!

**Comment by oyakata2438** [comment]
Twitterの方で皆さん回答いただきました・・・1/29でいきましょう。
次は場所とか、どんなところにするかとかですが、その前に売り上げ次第ですかねｗ
お店候補、あるいはジャンル希望どしどしください

**Comment by erukiti** [comment]
Twitterでもちらっと書きましたが、各自ダメなものを列挙。ダメじゃ無いものがあるお店を選ぶ感じですかね。無難に行くと居酒屋なんですが。

僕はダメなモノは無いです(納豆くらい)。
個人的な好みを言うと、海鮮と日本酒の美味しいお店ですかね！

**Comment by oyakata2438** [comment]
打ち上げ（1回目）終わったので、閉じますw
皆様、まずはお疲れ様でした。
また飲みましょう。
