### ISSUE TITLE
本文中で言及した設定ファイルの置き場所

### ISSUE THREAD

**Issue by degawa** [onestop-techbook/c93-onestop-techbook#96]
第9章で言及したPowerPointスライドを画像に変換する時の解像度設定について，設定を記録したレジストリの登録ファイル(*.regファイル)をリポジトリに置きたいのですがよろしいでしょうか？
/articlesの下にmaterialsというディレクトリを掘って置きたいと考えています．

1．置いてよいかどうか
2．置いてよい場合に，置き場所やディレクトリ名が相応しいかどうか
以上2点ご審議ください．

**Comment by oyakata2438** [comment]
問題ないかと思います。
また、説明は適当に作ってくだればw

**Comment by degawa** [comment]
承知しました．
では後ほどプルリクを送ります．
